# Generated by Django 3.1.6 on 2021-02-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('slug', models.SlugField(blank=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='عکس')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('status', models.CharField(choices=[('d', 'امانت گرفته شده'), ('p', 'موجود')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
                'ordering': ['-created'],
            },
        ),
    ]
