# Generated by Django 3.1.6 on 2021-02-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created'], 'verbose_name': 'امانت', 'verbose_name_plural': 'امانات'},
        ),
    ]
