# Generated by Django 3.1.6 on 2021-02-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_issue_applying_renew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='applying_renew',
        ),
    ]
